included: # paths to include during linting. `--path` is ignored if present.
  - Weather
  - WeatherTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
opt_in_rules:
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - identical_operands
  - implicit_return
  - last_where
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - trailing_closure
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration 
disabled_rules:
  - implicit_return
  - force_cast
  - trailing_whitespace
  - explicit_enum_raw_value
  - nesting
  - notification_center_detachment
  - class_delegate_protocol
  - identifier_name
  - closure_parameter_position
line_length: 160
file_length:
  warning: 500
function_body_length: 50